### DISCUSSION TITLE
Problem while using parameters within yaml file

### DISCUSSION THREAD

**Discussion by abhijeetdhakane** [omry/omegaconf#1017] [Q&A]
I have yaml file:
`train_data.yaml`

```
data_hparams:
  cutoff: 2.0
  classes: 4


_target_: src.datamodules.datamodule.DataModule
datasets:
  train:
    _target_: src.datamodules.components.dataloader.custom_loader
    fnames: ['${paths.data_dir}/train/test.txt']
    cutoff: data_hparams.cutoff
    classes: data_hparams.classes

  val:
    _target_: src.datamodules.components.dataloader.custom_loader
    fnames: ['${paths.data_dir}/val/test.txt']
    cutoff: data_hparams.cutoff
    classes: data_hparams.classes

  test:
    _target_: src.datamodules.components.dataloader.custom_loader
    fnames: ['${paths.data_dir}/test/test.txt']
    cutoff: data_hparams.cutoff
    classes: data_hparams.classes
```

Even after giving hints `cutoff: float, n_classes: int` while reading values in `src.datamodules.components.dataloader.custom_loader`

I am getting error, that above values are `str`

**Comment by Jasha10** [comment]
Try replacing `cutoff: ${data_hparams.cutoff}` with `cutoff: data_hparams.cutoff` and `classes: data_hparams.classes` with `classes: ${data_hparams.classes}`.

Please see the OmegaConf docs on [interpolation](https://omegaconf.readthedocs.io/en/2.2_branch/usage.html#variable-interpolation).

**Reply by abhijeetdhakane** [reply]
Thanks, worked out!!

I think this case is also a good example, variable within same node reused.

```
_target_: src.models.mnist_module.MNISTLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.simple_dense_net.SimpleDenseNet
  input_size: 784
  lin1_size: 64
  lin2_size: 128
  lin3_size: 64
  output_size: 10

train_params:
  out_sizes: ${..net.output_size}
```

**Reply by abhijeetdhakane** [reply]
I am not sure what was the wrong but you're recommendation did not worked out (I accidentally ran other working yaml config, and I thought it worked out).

But this is worked for me:
```
data_hparams:
  cutoff: 2.0
  classes: 4


_target_: src.datamodules.datamodule.DataModule
datasets:
  train:
    _target_: src.datamodules.components.dataloader.custom_loader
    fnames: ['${paths.data_dir}/train/test.txt']
    cutoff: ${...data_hparams.cutoff}
    classes: ${...data_hparams.classes}

  val:
    _target_: src.datamodules.components.dataloader.custom_loader
    fnames: ['${paths.data_dir}/val/test.txt']
    cutoff: ${...data_hparams.cutoff}
    classes: ${...data_hparams.classes}

  test:
    _target_: src.datamodules.components.dataloader.custom_loader
    fnames: ['${paths.data_dir}/test/test.txt']
    cutoff: ${...data_hparams.cutoff}
    classes: ${...data_hparams.classes}
```
