### DISCUSSION TITLE
How to I get the full key of a config?

### DISCUSSION THREAD

**Discussion by cyber-distillery** [omry/omegaconf#1062] [Q&A] [answered]
I have a yaml file which has nested structure as indicated below, when accessing the values via omegaconf, how would I also get the full key path?

For example, if I have a function that access `fruits.apple.price` which would give me `3.99`, how do I also print the key path `fruits.apple.price`?

```yaml
fruits:
  apple:
    price: 3.99
    status: green
    contract: 15-12-2025
  orange:
    price: 4.99
    status: red
    contract: 22-10-2023
```
