### DISCUSSION TITLE
Relative access in a list

### DISCUSSION THREAD

**Discussion by fbhdr** [omry/omegaconf#897] [Q&A] [answered]
**Is your feature request related to a problem? Please describe.**
yaml file:
```
foo:
  bar: 3
  a: ${foo.bar}
  b: ${.bar}
  c: [2, "${foo.bar}"]
  d: [2, "${.bar}"]  # This line leads to an error
```
Python script:
```
conf = OmegaConf.load('debug.yaml')
OmegaConf.resolve(conf)
```
Then there is an error due to `d: [2, "${.bar}"]`:
```
omegaconf.errors.InterpolationResolutionError: TypeError raised while resolving interpolation: Index 'bar' (str) is not an int
```

**Describe the solution you'd like**
I want to use relative access in list, i.e. can use `${.bar}` in a list `[xxx, xxx, xxx]`.

**Comment by Jasha10** [comment]
Hi @fbhdr,
Please give the following a try:
```yaml
foo:
  bar: 3
  a: ${foo.bar}
  b: ${.bar}
  c: [2, "${foo.bar}"]
  d: [2, "${..bar}"]
```
Using two dots in `${..bar}` is necessary because the list counts as an additional level of nesting.

**Comment by loodvn** [comment]
Potentially related:
I have an index type error when I try relative interpolation within a list.

Steps to reproduce:
```yaml
foo: bar

my_list:
  - y: "pre-${foo}-post"
    z: "pre-${..foo}-post"
```

```python
conf = OmegaConf.load("example.yaml")
conf["list"][0]["y"]  # Returns "pre-bar-post"
conf["list"][0]["z"]  # Returns the following error:
```

Error:
```
File "/opt/conda/envs/benchmark/lib/python3.12/site-packages/omegaconf/omegaconf.py", line 1132, in _select_one
    raise TypeError(
omegaconf.errors.InterpolationResolutionError: TypeError raised while resolving interpolation: Index 'foo' (str) is not an int
    full_key: my_list[0].z
    object_type=dict
```
Let me know if I should open an issue. @Jasha10
