### ISSUE TITLE
error inspecting valid config

### ISSUE THREAD

**Issue by omry** [omry/omegaconf#10]
the following valid config throws an exception in the debugger when trying to inspect it.

```
defaults:
  - dataset: imagenet
  - model: alexnet
  - optimizer: nesterov
```
