### ISSUE TITLE
How can I resolve within a list?

### ISSUE THREAD

**Issue by famura** [omry/omegaconf#1027]
**Is your feature request related to a problem? Please describe.**
I guess this is more of a beginner's question that might lead to a feature request.

**Describe the solution you'd like**
I would like to write a config yaml that resolves multiple things within one list for one item, e.g.
``` yaml
foo:
  bar: [1, ${custom_resolver:thing_to_resolve1}, 2, 3, ${custom_resolver:thing_to_resolve1}]
  ...
```
You can assume that
``` yaml
foo:
  bar: ${custom_resolver:thing_to_resolve1}
  ...
```
already works.

**Describe alternatives you've considered**
None, yet. Maybe writing a custom resolver, but I really don't know if that is necessary.

**Comment by Jasha10** [comment]
Hi @famura,
I think the issue here is with the [`pyyaml`](https://github.com/yaml/pyyaml) library that OmegaConf uses as a backend. The problem is that the example you gave is not valid yaml.

Either of the following should work:
#### Option 1: Quoting the value to be resolved:
```yaml
foo:
  bar: [1, "${custom_resolver:thing_to_resolve1}", 2, 3, "${custom_resolver:thing_to_resolve1}"]
```

#### Option 2: Putting each list item on a new line
```yaml
foo:
  bar:
    - 1
    - ${custom_resolver:thing_to_resolve1}
    - 2
    - 3
    - ${custom_resolver:thing_to_resolve1}
```
