### ISSUE TITLE
Multiple relative interpolation

### ISSUE THREAD

**Issue by qmpzzpmq** [omry/omegaconf#1077]
as folling from documnet:

from: https://omegaconf.readthedocs.io/en/2.3_branch/usage.html
> Interpolations are absolute by default. Relative interpolation are prefixed by one or more dots: The first dot denotes the level of the node itself and additional dots are going up the parent hierarchy. e.g. ${..foo} points to the foo sibling of the parent of the current node.

but how to access the parent of parent of current?

**Comment by omry** [comment]
> Interpolations are absolute by default. Relative interpolation are prefixed by one or more dots: The first dot denotes the level of the node itself and additional dots are going up the parent hierarchy. e.g. ${..foo} points to the foo sibling of the parent of the current node.

**Comment by omry** [comment]
Please explain what you mean with an example.

**Comment by qmpzzpmq** [comment]
I had a yaml file like:
```
train:
    dataset: 
        mapper: "A"
    prcess_dps "B"
val:
    dataset:
        mapper: ${}
    prcess_dps ${..train.process.dataset}
```
I would like keep the val.dataset.mapper same with train.dataset.mappser. so the reletive interpolation should be go up to parent levels  twice. I didn find anyway to implement it

**Comment by omry** [comment]
```yaml
train:
    dataset: 
        mapper: A
    prcess_dps: B
val:
    dataset:
        mapper: ${...train.dataset.mapper}
    prcess_dps: ${..train.prcess_dps}
```
