### ISSUE TITLE
Support deep merging of configs

### ISSUE THREAD

**Issue by MatteoVoges** [omry/omegaconf#1080]
**Is your feature request related to a problem? Please describe.**
I don't know if it's a bug or the expected behavior in the project, but I have the following example:

I want to merge the following configurations:
```yaml
dict: 
  list:
    - entry_a1: val_a1
      entry_a2: val_a2
```
```yaml
dict: 
  list:
    - entry_b1: val_b1
      entry_b2: val_b2
```

If I merge them, I get: ( see full script and steps to reproduce below
```yaml
dict: 
  list:
    - entry_b1: val_b1
      entry_b2: val_b2
```

**Describe the solution you'd like**
However I would expect, that the configs get deep merged, so that I get
```yaml
dict: 
  list:
    - entry_a1: val_a1
      entry_a2: val_a2
    - entry_b1: val_b1
      entry_b2: val_b2
```
as the merged result. The order of the elements doesn't matter.

Is that already possible and I'm missing something or is this functionality not supported? 

**Describe alternatives you've considered**
The main thing with this feature is, that we have to check, if two types are __mergable__, so that not something like
```yaml
dict: 
  string: val
```
and
```yaml
dict: 
  list:
      - entry1
```
get merged, because the types `string` and `list` would be incompatible.

**Additional context**
<details>
<summary>Here is the full python script for you to reproduce the examples:</summary>

```python
from omegaconf import OmegaConf

source_a = """
dict: 
    list:
    - entry_a1: val_a1
      entry_a2: val_a2
"""

source_b = """
dict: 
    list:
    - entry_b1: val_b1
      entry_b2: val_b2
"""

cfg_a = OmegaConf.create(source_a)
cfg_b = OmegaConf.create(source_b)

cfg_merged = OmegaConf.merge(cfg_a, cfg_b)

print(OmegaConf.to_yaml(cfg_merged))
```

</details>
