### ISSUE TITLE
Differences between `to_object()` and `resolve()` 

### ISSUE THREAD

**Issue by MatteoVoges** [omry/omegaconf#1092]
**Describe the bug**
When I define a custom resolver with a new interpolation in it, it seems like the resolving behavior differs, depending which function I use. If this is intended, please explain why.

**To Reproduce**
Resolver:
```python
def example(key):
  return {"first": f"${{{key}.a}}", "second": f"{{{key}.b}}"}

OmegaConf.register_new_resolver("example", example)
```
I load some yaml in, containing the resolver:
```yaml
key:
  a: 1
  b: 2
test: ${example:key}
```

Now if I resolve the config with `OmegaConf.resolve()` I get `omegaconf.errors.UnsupportedValueType: Value 'dict' is not a supported primitive type`.

With `OmegaConf.to_object()` I get the **EXPECTED** result:
```yaml
key:
  a: 1
  b: 2
test:
  first: ${key.a}
  second: ${key.b}
```

If `resolve` would just do that, it would be fine, because then I can simply resolve twice.
My goal result is:
```yaml
key:
  a: 1
  b: 2
test:
  first: 1
  second: 2
```
which I can achieve at the moment with `OmegaConf.to_object(OmegaConf.create(OmegaConf.to_object(config)))`, but this is no good solution because of the unneccessary loading.

**Expected behavior**
I would expect, that the functions behave the same-

**Additional context**
- [X] OmegaConf version: latest (2.4.dev0)
- [X] Python version: 3.10.6
- [X] Operating system: Linux
- [X] Please provide a minimal repro
