### ISSUE TITLE
Duplicate Key Error

### ISSUE THREAD

**Issue by lordsoffallen** [omry/omegaconf#1194]
**Describe the bug**
Omega conf can't parse the valid yaml file with anchors defined. The following yaml throws duplicate key error for the section:
```
anthropic-cached: &anthropic-cache
    <<: *anthropic
```
When I replace that it works. That's a valid yaml format and key merging should happen

**To Reproduce**
```yaml
_models:
  anthropic: &anthropic
    type: &LLM LargeModel
    backend: anthropic
    model: claude-3-5-sonnet-20240620
    credentials: anthropic-api-key
    model_params: &model-params
      temperature: !!float 0.5
  anthropic-cached: &anthropic-cache
    <<: *anthropic
    model_params:
      <<: *model-params
      extra_headers:
        anthropic-beta: prompt-caching-2024-07-31
  google: &google
    type: *LLM
    backend: google
    model: google/gemini-1.5-pro
    model_params: *model-params
    backend_kwargs:
      region: europe-west1
      project_id: 546565-n0
  llama-v3p1: &llama-v3p1
    type: *LLM
    backend: fireworks
    model: accounts/fireworks/models/llama-v3p1-70b-instruct
    credentials: fireworks-api-key
    model_params:
      <<: *model-params
      max_tokens: 16384
```

**Expected behavior**
I expect omegaconf to read the file without errors.

**Additional context**
- [ ] OmegaConf version: 2.3.0
- [ ] Python version: Python 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0]
- [ ] Operating system: Ubuntu 22.04
