### ISSUE TITLE
Look into supporting Union in Structured configs

### ISSUE THREAD

**Issue by omry** [omry/omegaconf#144]

**Comment by omry** [comment]
Bouncing to 2.2.

**Comment by jieru-hu** [comment]
comments from receipe team:
> Does this Union support include the new syntax being introduced (eg. TypeA | TypeB) ?

**Comment by kandluis** [comment]
For context, this is the proposal (https://www.python.org/dev/peps/pep-0604/), which is introduced in Python 3.10 (which is now also made available at Meta).

It's a big readability win. I'd say it's of middle-to-low importance for us, but just checking if it'll work with the support here in hydra. I suspect so since I assume `Union[A, B, ...]` and `A | B | ...`  will translate to the same underlying node.

Thanks for thinking of this!

**Comment by Jasha10** [comment]
Yes, it should be possible to support PEP 604.

**Comment by peterdavidfagan** [comment]
Does there exist a workaround for this issue? I have model parameters like kernel dimension which have type `Union[int, Sequence[int]]` that is causing issues for omegaconf. 

```yaml
# input projection layer
  resnet:
    _target_: multi_modal_transformers.tokenizers.images.image_tokenizer.ResNetV2Block
    num_blocks: 2
    input_conv:
      _target_: flax.linen.Conv
      features: 64
      kernel_size: [12, 12]
      strides: [2, 2]
      padding: VALID
      use_bias: True
      dtype: ${dtype}
      param_dtype: ${param_dtype}
      kernel_init:
        _target_: flax.linen.initializers.he_normal
        dtype: ${param_dtype}
      bias_init:
        _target_: flax.linen.initializers.normal
        dtype: ${param_dtype}
```
