### ISSUE TITLE
Enhancement: Compact key support

### ISSUE THREAD

**Issue by omry** [omry/omegaconf#152]
## Compact keys
This will probably come in OmegaConf 2.1 as 2.0 is closed to new features at this time.

Given:
```yaml
hydra:
  sweeper:
    params:
      budget: 100
      num_workers: 10
```

Allow the same config to be represented by:

```yaml
hydra.sweeper.params:
  budget: 100
  num_workers: 10
```
## Compatibility considerations
This changes the semantic meaning of a key with a dot, from a 
```yaml
foo.bar: 10
```
to:
```yaml
foo:
  bar: 10
```

People using `.` in their keys now should be aware of it and ideally stop doing it (in 1.4 or 2.0).
OmegaConf 2.0 will add a deprecation warning that can be disabled by setting the environment variable `OC_DISABLE_DOT_ACCESS_WARNING` to the value "1".

To address this, there will be multiple opt out mechanisms (fully specification tbd).
some ideas:

- [x] Allow keys with dot by escaping the `.` : `foo\.bar`
- [ ] Possibly allow file level opt out via a special header
- [ ] Possibly allow API level opt out when loading the file or when constructing a DictConfig object.

**Comment by omry** [comment]
postponing for 2.1

**Comment by hadim** [comment]
I am using `omegaconf` to process Kubernetes YAML file. Some field (`nvidia.com/gpu`) requires to use a dot in its name. Example:

```yaml
        # Request a number of CPUs and GPUs
        resources:
          requests:
            cpu: "16"
            nvidia.com/gpu: 1
          limits:
            cpu: "16"
            nvidia.com/gpu: 1
```

Those fields are decided at the level of the Kubernetes specification.

Any thoughts about this?

**Comment by omry** [comment]
Thanks for reporting.
for now suppress the warning with the environment variable.

I am planning to allow for some opt-out mechanisms before finalizing compact key support.

At the very least, you will be able to escape the dot in your yaml file:
```yaml
        resources:
          requests:
            cpu: "16"
            nvidia\.com/gpu: 1
          limits:
            cpu: "16"
            nvidia\.com/gpu: 1
```

Is this sufficient for your use case?

You can check-out https://github.com/omry/omegaconf/pull/155/  and test this, it's already there.
