### ISSUE TITLE
utils.instantiate does not allow passing dictionaries as kwargs

### ISSUE THREAD

**Issue by jbragg** [omry/omegaconf#169]
Thanks for the helpful library!
Filing a bug in the `utils.instantiate` function.

Suppose I have a config group file
```yaml
model:
  class: models.Net
  params:
    some: 0
    values: 1
```

Let's say I want to pass in a dictionary to `models.Net` as follows:
`utils.instantiate(cfg.model, some_config_argument={'test': 'dict'})`

This will throw `KeyError: 'Accessing unknown key in a struct : model.params.test'`

from `params.merge_with(OmegaConf.create(kwargs))` in the instantiate function.
