### ISSUE TITLE
consider supporting interpolation of config nodes.

### ISSUE THREAD

**Issue by omry** [omry/omegaconf#26]
use case:
config.yaml
```yaml
foo:
  list: [1,2,3]
  bar: ${foo.list}
```
