### ISSUE TITLE
Indirect interpolation bug

### ISSUE THREAD

**Issue by omry** [omry/omegaconf#283]
Minimal example:

```yaml
transform:
  standard_transforms:
    pre_transforms:
    - transform: NormalizeScale
model:
  transforms: ${transform.standard_transforms}
dataset:
  pre_transforms: ${model.transforms.pre_transforms}
```

to trigger convert to container with OmegaConf.to_container().
