### ISSUE TITLE
Iterating where key values exist but value is not set

### ISSUE THREAD

**Issue by jgbos** [omry/omegaconf#288]
Say I have the `config.yaml` file for Hydra:
```yaml
defaults:
  - foo: null
  - bar: default
```
And the `bar/default.yaml` file is
```yaml
bar:
  val1: ${foo}
  val2: 2
```

Then
```python
False == 'val1' in cfg.bar
True == 'val1' in cfg.bar.keys()
```

and if you try
```python
for k, v in cfg.bar.items():
  ...
```
it will raise the `ConfigKeyError`

FYI, this happens when trying to load the parameters into tensorboard.
