### ISSUE TITLE
Current yaml loader can't support merge syntax <<

### ISSUE THREAD

**Issue by roytseng-tw** [omry/omegaconf#323]
When load yaml file with merge syntax `<<`, will have the error: `yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:merge' `

```yaml
base: &base
  qqq: cry

General:
  <<: *base
```

This may be caused by the customized loader:
https://github.com/omry/omegaconf/blob/7d5f8fca92119119c3a41c38daddf254d4cf07a5/omegaconf/_utils.py#L84

Possibly related issue:
https://github.com/marcy-terui/lamvery/issues/73#issue-218862548

**Comment by omry** [comment]
Can you show me where in the yaml specification this is described? I generally see that pyyam is not particularly friendly to this [here](https://github.com/yaml/yaml/issues/35).

If what you are after in the final result is:
```yaml
base:
  qqq: cry

General:
  qqq: cry
```

You can easily achieve in OmegaConf with:
```yaml
base:
  qqq: cry

General: ${base}
```

For example:
```python
print(OmegaConf.create({"base": {"qqq": "cry"}, "General" : "${base}"}).pretty(resolve=True))
base:
  qqq: cry
General:
  qqq: cry
```
This is actually more powerful than what any yaml parser can do because this is resolved at runtime. This means it works across different yaml files that are merged together with OmegaConf.merge().

**Comment by roytseng-tw** [comment]
Here is the yaml spec: https://yaml.org/type/merge.html

What I tried to do is actually something like this:
**merge the value of a node with the value of other node**
```
base: &base
  qqq: cry

General:
  <<: *base
  happy: smile
```
Above will result in the following
```
base: &base
  qqq: cry

General:
  qqq: cry
  happy: smile
```

Moreover, with hydra (& omegaconf)
I would like to update the keys of a config node instead of overwritting it.
```yaml
# defaults.yaml
defaults:
  # ResNet is a config group option for config group `model`
  - model : ResNet
  - config.yaml
```
```
# config.yaml
# @package _global_
model_new:
  <<: ${model}
  description: "blah blah"
model: ${model_new}
```

**Comment by omry** [comment]
I have to tell you that so far I have not even been aware of this merge operator in yaml.
Since it has to work just like * and &, it's not really sufficient to merge across different files (which is what you are actually doing here using interpolation).
OmegaConf.merge(), which is what Hydra is using under the hood on your defaults list should be more than enough to do what you are after correctly.
In fact, I am happy that his does not work because this is just not good enough and merge is the way to go.

What about something like this?

*config.yaml*:
```yaml
defaults:
  - model : ResNet

model:
  description: "blah blah"
```

The resulting model node would be marge of the model node from resnet and the model node from your config.
Note that the composition order here is that config yaml comes before resnet. if you want your overriding node to override things in resnet you can do something similar to your example:
config.yaml:
```yaml
defaults:
  # ResNet is a config group option for config group `model`
  - model : ResNet
  - experiment: exp1
```

experiment/exp1.yaml:
```yaml
model:
  description: "blah blah"
```
