### ISSUE TITLE
Variable interpolation breaks after key updates

### ISSUE THREAD

**Issue by inmoonlight** [omry/omegaconf#369]
I managed `configs` separately by its characteristics. For example,
```
.
├── dataset
│   └── wmt14.deen.yaml
├── model
│   └── transformers.yaml
└── tokenizer
    ├── sentencepiece_bpe_wmt14_deen.yaml
    └── sentencepiece_bpe_wmt14_enfr.yaml
```

For the `dataset/wmt14.deen.yaml`, I used variable interpolation as follows:
```
name: wmt14.de-en
source_lang: en
target_lang: de

path:
    source_train: dataset/${name}.train.norm.${source_lang}
    source_dev: dataset/${name}.dev.norm.${source_lang}
    source_test: dataset/${name}.test.norm.${source_lang}
    target_train: dataset/${name}.train.norm.${target_lang}
    target_dev: dataset/${name}.dev.norm.${target_lang}
    target_test: dataset/${name}.test.norm.${target_lang}
```

In practice, I create a new config to deal with dataset, model, tokenizer configs all at once.
```python
from omegaconf import OmegaConf

dataset_configs = OmegaConf.load('dataset/wmt14.deen.yaml`)
tokenizer_configs = OmegaConf.load('tokenizer/sentencepiece_bpe_wmt14_deen.yaml`)
model_configs = OmegaConf.load('model/transformers.yaml`)

configs = OmegaConf.create()
configs.update(dataset=dataset_config, tokenizer=tokenizer_config, model=model_config)
```
During the above process, `name: wmt14.de-en` has changed to `dataset: \n name: wmt14.de-en`, and this breaks variable interpolations.

When I load the above `yaml` by itself, there's no error, as expected.
```python
>>> from omegaconf import OmegaConf
>>> dataset_configs = OmegaConf.load('dataset/wmt14.deen.yaml`)
>>> dataset_configs.path.source_train
'dataset/wmt14.de-en.train.norm.en'
```

However, when it comes to configs ConfigKeyError occurs.
```python
>>> configs.dataset.path.source_train
---------------------------------------------------------------------------
ConfigKeyError                            Traceback (most recent call last)
<ipython-input-16-5e4f5180b47b> in <module>
----> 1 configs.dataset.path.source_train

~/.pyenv/versions/3.6.9/envs/hephaestus/lib/python3.6/site-packages/omegaconf/dictconfig.py in __getattr__(self, key)
    295             return self._get_impl(key=key, default_value=DEFAULT_VALUE_MARKER)
    296         except Exception as e:
--> 297             self._format_and_raise(key=key, value=None, cause=e)
    298
    299     def __getitem__(self, key: Union[str, Enum]) -> Any:

~/.pyenv/versions/3.6.9/envs/hephaestus/lib/python3.6/site-packages/omegaconf/base.py in _format_and_raise(self, key, value, cause, type_override)
     99             msg=str(cause),
    100             cause=cause,
--> 101             type_override=type_override,
    102         )
    103         assert False

~/.pyenv/versions/3.6.9/envs/hephaestus/lib/python3.6/site-packages/omegaconf/_utils.py in format_and_raise(node, key, value, msg, cause, type_override)
    673         ex.ref_type_str = ref_type_str
    674
--> 675     _raise(ex, cause)
    676
    677

~/.pyenv/versions/3.6.9/envs/hephaestus/lib/python3.6/site-packages/omegaconf/_utils.py in _raise(ex, cause)
    589     else:
    590         ex.__cause__ = None
--> 591     raise ex  # set end OC_CAUSE=1 for full backtrace
    592
    593

ConfigKeyError: str interpolation key 'name' not found
        full_key: dataset.path.source_train
        reference_type=Any
        object_type=dict
```

---
I found `omegaconf` is really convenient, and appreciate for the amazing package! :)
