### ISSUE TITLE
[Feature Request] Add ability to get parts (sub-trees) of the config

### ISSUE THREAD

**Issue by 3janeAI** [omry/omegaconf#42]
Currently in OmegaConf, for the following config:
```
server:
  host: localhost
  port: 80

client:
  url: http://${server.host}:${server.port}/
  server_port: ${server.port}
```

We can get `conf["server"]` and `conf["client"]`, but then we lose the parent component name (e.g., "server" or "client").

This feature is to be able to get complete subtrees, rooted at the specified head.

Example config:
```
server:
  host: localhost
  port: 80

client:
  url: http://${server.host}:${server.port}/
  server_port: ${server.port}
```

Usage:
```
print(conf.root_from("server"))
```

Outputs
```
server:
  host: localhost
  port: 80
```
