### ISSUE TITLE
open_dict change value to the inherited value

### ISSUE THREAD

**Issue by omry** [omry/omegaconf#47]
for a nested config:
```yaml
foo:
  bar:
    baz: 10
```
if foo is struct, and we do
```python
with open_dict(cfg.foo.bar):
   bar.baz = 20
```

the struct flag of foo.bar would be changed to True.
