### ISSUE TITLE
RFC: relative interpolations

### ISSUE THREAD

**Issue by omry** [omry/omegaconf#48]
This seems like a useful extension:
```yaml
flap: 99

baz:
  flaf: 100

foo:
  bar: 10
  a: ${foo.bar}     # 10, absolute
  b: ${.bar}        # 10, relative
  c: ${..flap}      # 99, relative, level up
  d: ${..baz.flaf}  # 100, level up and then and then dig into baz
```

**Comment by omry** [comment]
@swist, any thoughts?

**Comment by swist** [comment]
What would be a prototypical use case?
Currently it seems like you can do all of these with a fully qualified namespace which I find easier to read.

**Comment by omry** [comment]
Here is a real example where this can be easier to read:
```yaml
dict:
  class: ..
  params:
    ...
    tokenizers:
      nltk:
        # sets language for the punkt (nltk) sentence tokenizer
        language: english
        file: "tokenizers/punkt/${dict.params.tokenizers.nltk.language}.pickle"
```

With relative interpolations, this can be:
`file: "tokenizers/punkt/${.language}.pickle"` which is much nicer.

Also consider something like:
```yaml
foo:
   baz:
     dict:
         default_bar: 10
         a:
            name: a
            bar: ${..default.bar} 
         b:
            name: b 
            bar: ${..default.bar} 
```
versus having ${foo.baz.dict.default_bar} twice.

**Comment by omry** [comment]
another advantage is that it makes things more portable.
with relative includes, you can move dict in the second example to be under foo without having to fix the interpolations.

**Comment by wolterlw** [comment]
+1 to portability
currently to test a specific sub-module it is still necessary to generate config for the whole project.

**Comment by omry** [comment]
can you give more context about your use case?

**Comment by wolterlw** [comment]
so I’m using hydra to configure my deep learning model training process.
When developing and debugging modules I often use Jupyter notebook, as it gives me a lot more flexibility.
Therefore I also want to load only those configs that are relevant to the specific module.

**Comment by omry** [comment]
I hope you are using the Compose API?
can you show a small example of where relative interpolation would help you?

**Comment by wolterlw** [comment]
Not sure about ComposeAPI, because I don't use omegaconf by itself, but rather through hydra.
Here's an example project structure:
```
├── config.yaml
├── main.py
├── data
│   ├── data_loader.py
│   └── dset_config.yaml
└── trainer
    ├── trainer_config.yaml
    └── trainer.py
```
In my dset_config.yaml I might have something like
```
d1_root: "~/data/dataset_1"
d2_root: "~/data/dataset_2"

dataset_files:
  train:
    d1: "${.d1_root}/train.npz"
    d2: "${.d2_root}/train.npz"
  valid:
    d1: "${.d1_root}/valid.npz"
    d2: "${.d2_root}/valid.npz"
```
currently instead of `${d1_root}` I have to specify `${data.d1_root}`, and have to load config.yaml, instead of just loading dset_config.yaml when I work with `data_loader.py`

**Comment by omry** [comment]
Okay, the Hydra Compose API is [here](https://hydra.cc/docs/experimental/compose_api).

Your example is wrong, you will need to access the field in absolute path:
```yaml
d1_root: "~/data/dataset_1"

dataset_files:
  train:
    d1: "${d1_root}/train.npz"
```

**Comment by wolterlw** [comment]
ok, I see how ComposeAPI does solve my problem.
You mean in absolute path like this?
```yaml
d1: "${data.d1_root}/train.npz"
```
because if I simply leave it without `data.` it won't parse in the main app

**Comment by omry** [comment]
Yes. relative interpolation is useful if you have:
```yaml
foo:
  bar: 10
  relative: ${.bar}        # 10
  absolute: ${foo.bar}     # 10
```

Note that this makes sense because `bar` is a sibling of `b`.

**Comment by wolterlw** [comment]
I get it
in my case it would be 
```yaml
d1_root: "/some/path"

data:
  d1: "${..d1_root}/file.npz"
```

**Comment by omry** [comment]
yes, except you can still use absolute interpolation which is cleaner for something like this:
```yaml
d1_root: "/some/path"
data:
  d1: "${d1_root}/file.npz"
```

Currently, all interpolations are absolute. interpolations that starts with a `. ` will get special treatment after this is implemented.
