### ISSUE TITLE
Allow "default" in interpolation when target config node does not exist

### ISSUE THREAD

**Issue by ppwwyyxx** [omry/omegaconf#541]
Currently, when the key in interpolation doesn't exist, e.g. in:
```python
dic = DictConfig({
        "c": "${a}"
    })
print(dic.c)
```
it throws exception about "str interpolation key 'a' not found".
I hope there is a way to specify default values.

**Describe the solution you'd like**
the `env:` resolver already supports defaults: https://omegaconf.readthedocs.io/en/latest/usage.html#environment-variable-interpolation
and the syntax seems nice. 
The above can be written as:
```python
dic = DictConfig({
        "c": "${a,123}"
})
```

**Describe alternatives you've considered**

**Comment by omry** [comment]
Hi @ppwwyyxx.
While it may seem like a simple addition, changing something so fundamental has a very large surface area and will require careful evaluation of how it's interacting with many of the existing features (Structured Configs, config merging and so on).

This is something I can consider if there is more interest in this feature by additional users.

In the mean time, Can you motivate this more? I have never felt the need for something like this so far.

**Comment by ppwwyyxx** [comment]
To give an example, consider a config organization that looks like this:
```yaml
output_dir: "./output"

train_job:
  # other settings
  tensorboard_output_dir: "${output_dir}"
eval_jobs:
  - evaluator: Evaluator1
    #other settings
    predictions_output_dir: "${output_dir}"
  - evaluator: Evaluator2
    predictions_output_dir: "${output_dir}"
```

where a task is composed of multiple jobs that should share `output_dir`. 
This organization works, however when such a config is created by composition of separate smaller files (e.g. each describes one job), we hope that ideally each of these smaller config files can be __reused on its own__ (e.g., if I just want to create an evaluator from a config file `eval_jobs/evaluator1.yaml`). 

To be able to reuse this config independently, without the presence of the top-level `output_dir`, it's useful to give interpolation a default value of None or "./output".

**Comment by omry** [comment]
This is solved by Hydra using config composition.

config.yaml:
```yaml
defaults:
 - base
 - trainer
```

base.yaml:
```yaml
output_dir: "./output"
```
trainer.yaml:
```yaml
train_job:
  # other settings
  tensorboard_output_dir: "${output_dir}"
eval_jobs:
  - evaluator: Evaluator1
    #other settings
    predictions_output_dir: "${output_dir}"
  - evaluator: Evaluator2
    predictions_output_dir: "${output_dir}"
```
You can also merge base.yaml into config.yaml in this case:

config.yaml:
```yaml
defaults:
 - trainer

output_dir: "./output"
```

This way, you can override the output_dir in a single place that will effect all the different nodes that are interpolating to it.
Also, the nodes themselves can be overridden if they really need to be diverged from the default for some reason.
