### ISSUE TITLE
Support of merge key feature (tag:yaml.org,2002:merge)

### ISSUE THREAD

**Issue by espdev** [omry/omegaconf#575]
Hello,

I'm trying to replace our own yaml-based configuration system to omegaconf. I'm having difficulties with loading existing yaml configuration files.

I have files like this:

```yaml
default: &default_params
  foo: 1
  bar: 2

some:
  <<: *default_params
  spam: 3
```

And it seems, omegaconf does not support merge key [feature](https://yaml.org/type/merge.html). I'm getting the following error when using `OmegaConf.load`:
```
ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:merge'
  in "/path/to/config.yaml", line 6, column 2
```

At the same time the default yaml loader from pyyaml works fine with above yaml file.

Could you support this feature? Or maybe your variable interpolation feature can be used instead?
