### ISSUE TITLE
Interpolation breaking change, scope of interpolation (is this intentional?)

### ISSUE THREAD

**Issue by saulzar** [omry/omegaconf#690]
**Describe the bug**

I have some config file which looks like this (used from hydra). I'm trying out the latest hydra dev installed with --pre. (1.1.0dev5), with omegaconf (2.1.0dev24), I tried 25 as well and has the same behavior.

```
camera:
  rotation: [0, 90, 0]

  cameras:
    - name: cam1
      location: [0, 0.0, 0.26]
      rotation: ${camera.rotation}
    - name: cam2
      location: [0, 0.0, 0.26]
      rotation: ${camera.rotation}

```
It no longer finds `camera.rotation`. I'm not sure why?
`omegaconf.errors.InterpolationKeyError: Interpolation key 'camera.rotation' not found`

Is this expected?
