### ISSUE TITLE
Possible inclusion of an unsafe mode (keeping built-in container types)

### ISSUE THREAD

**Issue by Dekakhrone** [omry/omegaconf#733]
Hi there! Thanks for the great tool! 

However, in my opinion, there is not enough flexibility on one issue. I already ran into the fact that I can not carry out the concatenation of built-in list and ListConfig type objects, but this was resolved using the following code:
```python
dims = list(dims) if isinstance(dims, MutableSequence) else [dims]
in_dims, out_dims = [emb_dim] + dims, dims + [emb_dim]
```

Now I need to configure a network architecture, one of the blocks of which contains the following structure:
```
reference_encoder:
  filters: [32, 32, 64, 64, 128, 128]
  kernel: [3, 3]
  strides: [2, 2]
  pad: [1, 1]
  gru_size: 128
  activation: "relu"
```
and due to the fact that the lists in the omegaconf are represented by their own class, everything ends with an error (pytroch 1.7.0): 
```
TypeError: conv2d(): argument 'stride' (position 4) must be tuple of ints, not ListConfig
```
I tried to do the trick with recursive pass through the config and replace the ListConfig with an native lists, but, as I understand it, because of the built-in checks, the list is forcibly converted. Is it possible to somehow disable such checks?
