### ISSUE TITLE
Add a CITATION.cff file to enable github support for citations to software

### ISSUE THREAD

**Issue by sugatoray** [omry/omegaconf#782]
![image](https://github.blog/wp-content/uploads/2021/08/github-citation-screenshot.png?w=1200)

## **Is your feature request related to a problem? Please describe.**
GitHub now supports (natively) defining citations to use software repositories on hosted on the platform. Alike the `LICENSE` file, in this case, you essentially add a `CITATION.cff` file (formatted as yaml) to the repository root. And that creates the citations feature for the repository: you can get it as `bibtex` or in `APA style`.

## **Describe the solution you'd like**
I would like to add the citations file to a new branch (in sugatoray/omegaconf) and push it to `omry/omegaconf@master`. 

## **Describe alternatives you've considered**
Additionally, you could also consider adding the bibtex to the readme file (assuming this being a relatively new feature of GitHub, not a lot of users may be aware of it yet).

```bibtex
@misc{Yadan_omegaconf_2021,
author = {Yadan, Omry},
month = {8},
title = {{omegaconf}},
url = {https://github.com/omry/omegaconf},
year = {2021}
}
```

## **Additional context**
Useful Links:

- [Enhanced support for citations on GitHub](https://github.blog/2021-08-19-enhanced-support-citations-github/)
- [What is a CITATION.cff file?](https://citation-file-format.github.io/)
- [Demo gif - LinkedIn Share](https://www.linkedin.com/posts/github_enhanced-citation-support-on-github-activity-6834161054352850944-LRDT)
- [Create your own citation.cff](https://citation-file-format.github.io/cff-initializer-javascript/)

### **Single Author**

```yml
# file: CITATION.cff
cff-version: 1.2.0
message: "If you use this software, please cite it as below."
authors:
- family-names: "Yadan"
  given-names: "Omry"
  orcid: "https://orcid.org/0000-0000-0000-0000"
title: "omegaconf"
version: 2.1.1
doi: 10.5281/zenodo.1234
date-released: 2021-08-17
url: "https://github.com/omry/omegaconf"
```

### **Multiple Authors**

```yml
# file: CITATION.cff
cff-version: 1.2.0
message: "If you use this software, please cite it as below."
authors:
- family-names: "Yadan"
  given-names: "Omry"
  orcid: "https://orcid.org/0000-0000-0000-0000"
- family-names: "Yadan2"
  given-names: "Omry2"
  orcid: "https://orcid.org/0000-0000-0000-0001"
- family-names: "Yadan3"
  given-names: "Omry3"
  orcid: "https://orcid.org/0000-0000-0000-0002"
title: "omegaconf"
version: 2.1.1
#doi: 10.5281/zenodo.1234
date-released: 2021-08-17
url: "https://github.com/omry/omegaconf"
```

## Questions

@omry Before I push the PR, I thought of posing the following questions. It's also better to have an [**`orcid`**](https://orcid.org/) for each author. So, author(s) who do not have any orcid, I would suggest them creating one. If there will be more than one authors, please provide a list below.

- Will there be single or multiple authors?
- How to update the version and release dates in future in the CITATION.cff file? How about using Jinja templating to automate this? Or, a simple python script?
