### ISSUE TITLE
OmegaConf is vulenrable to ddos via specially crafted yaml input (billion laughs attack)

### ISSUE THREAD

**Issue by omry** [omry/omegaconf#794]
OmegaConf is vulnerable to [Billion laughs attack](https://en.wikipedia.org/wiki/Billion_laughs_attack).
Specially crafted yaml input files can use yaml anchors to create a yaml input that is fast to load but very slow to traverse because it contains billions of nodes.

This is considered medium priority and will be addressed in a future major version of OmegaConf.
Most potential fixes are breaking.

### Details
pyyaml is creating references to the same object when it loads an anchor, which is why it can do load such files quickly.

Example input:
```yaml
lol1: &lol1 "lol"
lol2: &lol2 [*lol1,*lol1,*lol1,*lol1,*lol1,*lol1,*lol1,*lol1,*lol1]
lol3: &lol3 [*lol2,*lol2,*lol2,*lol2,*lol2,*lol2,*lol2,*lol2,*lol2]
lol4: &lol4 [*lol3,*lol3,*lol3,*lol3,*lol3,*lol3,*lol3,*lol3,*lol3]
lol5: &lol5 [*lol4,*lol4,*lol4,*lol4,*lol4,*lol4,*lol4,*lol4,*lol4]
lol6: &lol6 [*lol5,*lol5,*lol5,*lol5,*lol5,*lol5,*lol5,*lol5,*lol5]
lol7: &lol7 [*lol6,*lol6,*lol6,*lol6,*lol6,*lol6,*lol6,*lol6,*lol6]
lol8: &lol8 [*lol7,*lol7,*lol7,*lol7,*lol7,*lol7,*lol7,*lol7,*lol7]
lol9: &lol9 [*lol8,*lol8,*lol8,*lol8,*lol8,*lol8,*lol8,*lol8,*lol8]
lol10: &lol10 [*lol9,*lol9,*lol9,*lol9,*lol9,*lol9,*lol9,*lol9,*lol9]
```

Such input creates billions of yaml nodes. OmegaConf will take an unreasonably long time to instantiate an object from it.

#### 1. Use interpolations instead of yaml anchors
Avoid yaml anchors and use interpolations instead.

The following config uses interpolations to achieve a similar behavior:

```yaml
lol1: "lol"
lol2: ["${lol1}","${lol1}","${lol1}","${lol1}","${lol1}","${lol1}","${lol1}","${lol1}","${lol1}"]
lol3: ["${lol2}","${lol2}","${lol2}","${lol2}","${lol2}","${lol2}","${lol2}","${lol2}","${lol2}"]
lol4: ["${lol3}","${lol3}","${lol3}","${lol3}","${lol3}","${lol3}","${lol3}","${lol3}","${lol3}"]
lol5: ["${lol4}","${lol4}","${lol4}","${lol4}","${lol4}","${lol4}","${lol4}","${lol4}","${lol4}"]
lol6: ["${lol5}","${lol5}","${lol5}","${lol5}","${lol5}","${lol5}","${lol5}","${lol5}","${lol5}"]
lol7: ["${lol6}","${lol6}","${lol6}","${lol6}","${lol6}","${lol6}","${lol6}","${lol6}","${lol6}"]
lol8: ["${lol7}","${lol7}","${lol7}","${lol7}","${lol7}","${lol7}","${lol7}","${lol7}","${lol7}"]
lol9: ["${lol8}","${lol8}","${lol8}","${lol8}","${lol8}","${lol8}","${lol8}","${lol8}","${lol8}"]
lol10: ["${lol9}","${lol9}","${lol9}","${lol9}","${lol9}","${lol9}","${lol9}","${lol9}","${lol9}"]
```

Note that the config is still too big for actual traversal but since it's evaluated lazily it's possible to use it if it's done carefully.

#### 2. Validate object created by pyyaml
If the config cannot be trusted, a check can be made before instantiating OmegaConf from a dict (instead of from a file) with a function similar to this:

```python
def check_no_refs(obj, memo=None):
    if memo is None:
        memo = set()
    if isinstance(obj, dict):
        c = 0
        for k, v in obj.items():
            c = c + check_no_refs(v, memo)
        return c
    if isinstance(obj, list):
        c = 0
        for v in obj:
            c = c + check_no_refs(v, memo)
        return c
    else:
        idv = id(obj)
        if idv in memo:
            raise RuntimeError("duplicate item added")
        memo.add(idv)
        return 1


with io.open(os.path.abspath("1.yaml"), "r", encoding="utf-8") as f:
    obj = yaml.load(f)

check_no_refs(obj)
# Create cfg after checking dict returned by pyyaml
cfg = OmegaConf.create(obj)
```

### Possible future OmegaConf solutions

The following are possible strategies to handle it inside OmegaConf.
1. Deprecate yaml anchors in favor of interpolations (detect usage of anchors and issue a warning telling the user to use interpolations instead
2. Automatically convert detected anchors to interpolation, this is potentially tricky
3. Limit config loaded to yaml files/strings to a maximum number of nodes and issue an error (10k or even 50k nodes seems like plenty).
4. Provide an API allowing safe usage by rejecting all anchors. default behavior is TBD.
