### ISSUE TITLE
Structured config created from subclass of dataclass does not have correct initial values

### ISSUE THREAD

**Issue by Jasha10** [omry/omegaconf#817]
**Describe the bug**
When an omegaconf structured config is created from a subclass of a dataclass, the config is not initialized with the default values from the subclass; instead the default values from the superclass are used.

**To Reproduce**
```python
from dataclasses import dataclass, field
from typing import Any, Dict, List

from omegaconf import MISSING, OmegaConf


@dataclass
class ParentConfig:
    model_depth: int = MISSING
    model_list: List[int] = field(default_factory=lambda: [5, 6])
    model_list_2: List[int] = MISSING
    model_dict: Dict[str, Any] = MISSING


@dataclass
class ChildConfig(ParentConfig):
    model_depth: int = 5
    model_list_2: List[int] = field(default_factory=lambda: [1, 2, 3])
    model_dict: Dict[str, Any] = field(default_factory=lambda: {"a": 5, "b": 6})


cfg = OmegaConf.structured(ChildConfig)
print(OmegaConf.to_yaml(cfg))
```
```yaml
# Actual Output:

model_depth: 5
model_list:
- 5
- 6
model_list_2: ???
model_dict: ???

# Expected Output:

model_depth: 5
model_list:
- 5
- 6
model_list_2:
- 1
- 2
- 3
model_dict:
  a: 5
  b: 6
```

This is a `dataclass` issue; when using `attr` classes instead of `dataclasses`, there is no bug.

**Additional context**
- Based on this issue: https://github.com/facebookresearch/hydra/issues/1881
