### ISSUE TITLE
Relative access in a list

### ISSUE THREAD

**Issue by fbhdr** [omry/omegaconf#895]
**Is your feature request related to a problem? Please describe.**
yaml file:
```
foo:
  bar: 3
  a: ${foo.bar}
  b: ${.bar}
  c: [2, "${foo.bar}"]
  d: [2, "${.bar}"]  # This line leads to an error
```
Python script:
```
conf = OmegaConf.load('debug.yaml')
OmegaConf.resolve(conf)
```
Then there is an error due to `d: [2, "${.bar}"]`:
```
omegaconf.errors.InterpolationResolutionError: TypeError raised while resolving interpolation: Index 'bar' (str) is not an int
```

**Describe the solution you'd like**
I want to use relative access in list, i.e. can use `${.bar}` in a list `[xxx, xxx, xxx]`.
