### ISSUE TITLE
Does oc.dict.values preserve order?

### ISSUE THREAD

**Issue by will-gp** [omry/omegaconf#982]
I am wondering if `oc.dict.values` preserves order.

Given the following example:

pets.yaml
```
zebra:
    - name: Bob
    - age: 24
cat:
    - name: Louis
    - age: 5
```

and another yaml file which uses `pets.yaml`:
```
defaults:
  - pets

profile:
   - ${oc.dict.values:pets}
```

will `oc.dict.values` preserve the order of the objects in `pets.yaml`?
ie. the order will **always** be the values of [zebra,cat] and never [cat, zebra]
