### ISSUE TITLE
Wrong exception on indirect access to missing value

### ISSUE THREAD

**Issue by omry** [omry/omegaconf#99]
```yaml
foo:
  bar: ???
  foo: ${bar}
```

```python
cfg = OmegaConf.create(..)
cfg.foo # should throw MissingMandatoryValue but throws KeyError
```
